[package]
name = "websockettest"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { version = "*", features = ["websocket"]}
tokio = { version = "*", features = ["rt-multi-thread", "macros"] }
futures-util = "0.3.17"

[profile.release]
strip = "symbols"
opt-level = 3
lto = true
